demo/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('myapps.app.urls')),
]

myapps/app/urls.py
from django.urls import path
from . import views


app_name = 'app'


urlpatterns = [
    path('', views.index, name='index'),
    path('save/', views.add_update, name='add'),
    path('save/<int:emp_id>/', views.add_update, name='update'),
]

myapps/app/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver


# Create your models here.
class Employee(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    address_1 = models.CharField(max_length=255)
    address_2 = models.CharField(max_length=255)
    city = models.CharField(max_length=100)
    state = models.CharField(max_length=100)
    zip = models.CharField(max_length=20)

    def __str__(self):
        return self.user.username


@receiver(post_save, sender=User)
def create_employee(sender, instance, created, **kwargs):
    if created:
        employee, created = Employee.objects.get_or_create(user=instance)

post_save.connect(create_employee, sender=User)

myapps/app/forms.py
from django import forms
from .models import Employee


class EmployeeForm(forms.ModelForm):
    user = forms.CharField(max_length=20, label='')

    class Meta:
        model = Employee
        exclude = ('user',)
        # fields = '__all__'
        labels = {
            'address_1': '',
            'address_2': '',
            'city': '',
            'state': '',
            'zip': '',
        }

    def __init__(self, *args, **kwargs):
        super(EmployeeForm, self).__init__(*args, **kwargs)
        instance = None

        try:
            instance = kwargs.pop('instance')
        except KeyError:
            pass

        if instance:
            self.fields['user'].widget.attrs['readonly'] = True

        field_names = [field_name for field_name, _ in self.fields.items()]
        for field_name in field_names:
            field = self.fields.get(field_name)
            field.widget.attrs.update(
                {
                    'class': 'form-control',
                    'placeholder': field_name.capitalize(),
                    'autocomplete': 'none',
                }
            )

myapps/app/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .forms import EmployeeForm
from .models import Employee
from django.contrib.auth.models import User


# Create your views here.
def index(request):
    employees = Employee.objects.all()
    return render(request, 'app/index.html', {'employees': employees})


def add_update(request, emp_id=0):
    if emp_id:
        user = get_object_or_404(Employee, id=emp_id)
        form = EmployeeForm(request.POST or None, instance=user, initial={"user": user})

    else:
        form = EmployeeForm(request.POST or None)

    if request.method == 'POST':
        if form.is_valid():
            form.save(commit=False)

            # Get the 'username' from the form
            # if not emp_id:
            username = request.POST.get('user')

            # Create the user with the 'username' as above which creates
            # the employee user as well. If the user exists, update the record
            if emp_id:
                user = User.objects.get(username=username)
                user.save()
            else:
                user = User.objects.create(username=username)

            # Now get the employee user and add/update the extra fields
            employee = Employee.objects.get(id=user.id)
            employee.address_1 = request.POST.get('address_1')
            employee.address_2 = request.POST.get('address_2')
            employee.city = request.POST.get('city')
            employee.state = request.POST.get('state')
            employee.zip = request.POST.get('zip')
            employee.save()

        # 'Employee' user saved - now redirect to index page
        return redirect('app:index')

    return render(request, 'app/add_update.html', {'form': form})

myapps/app/templates/_base.html
<!DOCTYPE html>
<html lang="en">

<head>
	<!-- Required meta tags -->
	<meta charset="utf-8">
	<meta name="description" content="Application by Aniket Aryamane">
	<meta name="author" content="Aniket Aryamane">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

	<title>{% block title %}{% endblock %}</title>
	<link rel="apple-touch-icon" href="">

	{% load static %}

	<!-- Link to Bootstrap CSS file -->
	<link rel="stylesheet" href="{% static 'app/css/vendor/bootstrap/bootstrap.min.css' %}" type="text/css">

	<!-- Link to Materialize CSS file -->
	<!-- <link rel="stylesheet" href="{% static 'app/css/vendor/materialize/materialize.min.css' %}" type="text/css"> -->

	<!-- Link to Font-Awesome CSS file -->
	<link rel="stylesheet" href="{% static 'app/css/vendor/font-awesome/css/all.css' %}" type="text/css">

	<!-- Link to your favicon.ico file -->
	<link rel="shortcut icon" href="{% static 'app/img/favicon.ico' %}" type="image/x-icon">

	<!-- Link to your css file -->
	<link rel="stylesheet" href="{% static 'app/css/main.css' %}" type="text/css">

</head>

<body>
	{% block content %}{% endblock %}


	<!-- Link to Materialize JS file -->
	<!-- <script src="{% static 'app/js/vendor/materialize/materialize.min.js' %}"></script> -->

	<!-- JQuery comes first in the list -->
	<script src="{% static 'app/js/vendor/bootstrap/jquery-3.4.1.min.js' %}"></script>
	<script src="{% static 'app/js/vendor/bootstrap/popper.min.js' %}"></script>
	<script src="{% static 'app/js/vendor/bootstrap/bootstrap.min.js' %}"></script>

	<!-- Link to your js file -->
	<script src="{% static 'app/js/main.js' %}"></script>

	<!-- Link to your extra javascript/jquery file -->
	{% block extra_js %}{% endblock %}
</body>

</html>

myapps/app/templates/app/add_update.html
{% extends '_base.html' %}
{% load static %}

{% block title %}
  App | Home
{% endblock %}

{% block content %}
  <div class="container">
    <h1 class="text-center my-4">Add Employee</h1>
    <form action="" method="POST" autocomplete="off">
      {% csrf_token %}
      <div class="form-group">
        {{ form.user.label_tag }}
        {{ form.user }}
      </div>
      <div class="form-group">
        {{ form.address_1.label_tag }}
        {{ form.address_1 }}
      </div>
      <div class="form-group">
        {{ form.address_2.label_tag }}
        {{ form.address_2 }}
      </div>
      <div class="form-group">
        <div class="row">
          <div class="col-md-4">
            {{ form.city.label_tag }}
            {{ form.city }}
          </div>
          <div class="col-md-4">
            {{ form.state.label_tag }}
            {{ form.state }}
          </div>
          <div class="col-md-4">
            {{ form.zip.label_tag }}
            {{ form.zip }}
          </div>
        </div>
      </div>
      <button type="submit" class="btn btn-outline-primary my-3" name="button">
        <i class="fas fa-database mr-2"></i>
        Save
      </button>
    </form>
  </div>
{% endblock %}

myapps/app/templates/app/index.html
{% extends '_base.html' %}
{% load static %}

{% block title %}
  App | Employee List
{% endblock %}

{% block content %}
  <a href="{% url 'app:add' %}" class="btn btn-outline-primary m-3">Add Employee</a>
  <div class="container">
    <div class="row">
      <div class="col-12">
        <h1 class="text-center mb-3">Employee List</h1>
      </div>
      <ul class="list-group list-group-flush">
        {% for employee in employees %}
          <li class="list-group-item">
            <a href="{% url 'app:update' emp_id=employee.id %}" class="text-decoration-none mx-2">
              {{ employee.user }}
            </a>
          </li>
          {% empty %}
          <h3 class="display-1">No Employees!!</h3>
        {% endfor %}
      </ul>
    </div>
  </div>
{% endblock %}